Development1
onedebos/nyt-clone pull request #6
Opened 2019-07-11 22:56 UTC by onedebos

2019-07-13 09:26 UTC, Ispirett commented
Hey folks great work so far on this project :100: There are some issues that need addressing.
- [ ] Use this https://validator.w3.org tool and  correct all the HTML errors 
- [ ] Some of the svgs are very big they are taking up a lot of the page please address this
- [ ]  Make the section under the Post image centered properly
- [ ] For the  'Read comments' button make sure its style and positioned properly 
- [ ] For the social icons next to the read comments button **Microverse** recommends the use of font awesome for icons link here https://fontawesome.com/
- [ ]

2019-07-13 10:09 UTC, bolah2009 requested changes
## Great Work Team! :clap:

This was an excellent effort!  :ok_hand: 
You are almost there! Only a few changes required. :blush:

To make the review even much easier for you, below are the checklist to consider the project 'complete' it must satisfy the following points:

#### Navigation bar

:heavy_check_mark:   It has a navigation bar

:heavy_check_mark:   It uses the `<nav>` tag

:heavy_check_mark:   It has a "Hamburger button", a search icon and a link with text on the leftmost side of the navbar

:heavy_check_mark:   has the NY Times image logo embedded in the center of the navbar

:recycle:  The NY Times logo is a link

:heavy_check_mark:   It has both, 'Subscribe' and 'Log in' elements with a `<button>` tag on the rightmost side of navbar

:heavy_check_mark:    The 'Subscribe' and 'Log in' buttons have a blue background and white letters

#### Bottom
:recycle:   It should have a 'Read comments' button and social media icons (fontawsome is recommended for the icons)

#### Additional Links
:recycle:  The section should be made of two parts: left side for links with images and right for links only

:recycle:  The left side is made of two parts: *More in Space and Cosmos* and *Editor's picks*

#### Footer
:recycle:  It includes the NYTimes logo as an embedded image in the top left corner of the footer

:recycle:  The NYTimes logo is a link

:recycle:  It includes a *go to homepage* link on the top right corner of the footer

:recycle:  The bottom part of the footer to includes links with copyright, TOC, contacts, and help


### Crucial things to make project works
:recycle:   Check page in web browser: nothing is messed up?

![Full Screenshot of web page](https://res.cloudinary.com/bolaah/image/upload/v1563012521/github-microverse-project/code-reviews/001.jpg)

#### Navigation bar
:recycle:   The Navbar should have a fixed position

:heavy_check_mark:     Floats or flex display for positioning items inside the navbar

#### Main Content
:heavy_check_mark:     The main content of the website should be wrapped with an HTML tag  `<main>`

:recycle:   The first image should be ~ 50% wider than the rest of the content inside `<main>`

:recycle:   All images and videos should be enclosed by a `<figure>` tag with `<figcaption>` that gives a description of the embedded image or video

:recycle:   Any sections that include text (paragraphs) should be wrapped with a `<section>` tag and include an `<aside>` tag for Editor's picks and a Sign-Up button.

#### Additional Links
:recycle:   The left side uses `<figure>` and `<figcaption>` tags followed by the title of the articles

:recycle:   `display: flex` or *float* are recommended

#### Footer
:heavy_check_mark:     The footer section is wrapped by a `<footer>` tag

:recycle:    Links should be organized using the `<ul>` tag and positioned with `display: flex` or *floats*


Keep up the good work and best of luck on the next submission. 👍

Happy Coding! :woman_technologist: :man_technologist:  :dizzy: and Have a Nice Day :smile:

Cheers,  
Bola

2019-07-13 10:09 UTC, bolah2009 commented on index.html
> +    </nav>
`AWESOME`

Great work using a `<nav>` tag for navigation bar, this helps to communicate meaning to the browser, developer, reader, and any other technologies interpreting the document (e.g. voice assistants). :ok_hand:

2019-07-13 10:09 UTC, bolah2009 commented on index.html
> +        <img class="nyt-heading" src="assets/svg-icons/svg2.svg">
`REQUIRED`

`The NY Times logo is a link` - The `<img>` element should be wrapped with a link.

-----


`SUGGESTION`

Consider adding an `alt` attribute to the `<img>` element, this is a very important accessibility attribute.
`Examples of scenarios where users benefit from text alternatives for images` are listed below and could also be found [here](https://www.w3.org/TR/html51/semantics-embedded-content.html#alt-text)

- They have a very slow connection and are browsing with images disabled.
- They have a vision impairment and use text to speech software.
- They have a cognitive impairment and use text to speech software.
- They are using a text-only browser.
- They are listening to the page being read out by a voice Web browser.
- They have images disabled to save on download costs.
- They have problems loading images or the source of an image is wrong.


##### SOURCE: [W3C Recommendation (Embedded Content)](https://www.w3.org/TR/html51/semantics-embedded-content.html#alt-text)

2019-07-13 10:09 UTC, bolah2009 commented on index.html
> +<head>
`SUGGESTION`

Consider adding `lang="en"` (or variant) to the `html` start tag, this is good for internationalisation. Also, check this [link for more info](https://www.w3.org/International/questions/qa-html-language-declarations#basics)

Take advantage of [HTML CHECKER](https://validator.w3.org) by checking your code with this online tool. It spots out common mistakes/omission in HTML codes. :+1:

2019-07-13 10:09 UTC, bolah2009 commented on index.html
> +        </section>
Please see [#1 Comment](https://github.com/onedebos/nyt-clone/pull/6#discussion_r303197464) on [HTML Checker](https://validator.w3.org/)

2019-07-13 10:09 UTC, bolah2009 commented on index.html
> +                <img src="assets/inflation-945.png" class="inflation-img">
Please see [#1 Comment](https://github.com/onedebos/nyt-clone/pull/6#discussion_r303197464) on [HTML Checker](https://validator.w3.org/) and [#2 Comment](https://github.com/onedebos/nyt-clone/pull/6#discussion_r303196769) on `<img>` tag `alt`

2019-07-13 10:09 UTC, bolah2009 commented on index.html
> +                    <p class="p-class" id="p8"><span">EXPANSION</span> Returning to our coffee, imagine a single, central pot expanding faster than light and cooling to an even
Please see [#1 Comment](https://github.com/onedebos/nyt-clone/pull/6#discussion_r303197464) on [HTML Checker](https://validator.w3.org/)

2019-07-13 10:09 UTC, bolah2009 commented on index.html
> +                </section> -->
Consider deleting commented out code, If you need to review a previous version of your code, use [git history](https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History).

2019-07-13 10:09 UTC, bolah2009 commented on index.html
> +    <main>
`AWESOME` 

Very good, using `main`, this shows the dominant content of the `<body>` of a document. More on `<main>` [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main) :star2: :star:

2019-07-13 10:09 UTC, bolah2009 commented on indexFILE.txt
> +<!DOCTYPE html>
I would suggest deleting this file. :thinking:

2019-07-13 10:09 UTC, bolah2009 commented on CSSFile.txt
> +*,::before,::after{
I would suggest deleting this file. :thinking:

2019-07-13 10:09 UTC, bolah2009 commented on styles.css
> +/*    justify-content: space-between;
Consider deleting commented out codes.

2019-07-13 10:09 UTC, bolah2009 commented on styles.css
> +    display: flex;
Consider adding `position: fixed;` to make the nav-bar fixed as required. This feature is useful with pages with long height, it makes it easier to navigate the page anywhere you are on the site.

2019-07-16 06:39 UTC, bolah2009 approved these changes
# Congratulations Team! :tada:

You've done an awesome Job :muscle:

I'm impressed and proud of your progress, you should be too :clap:

##### Before you merge checkout your [html code with this validator](https://validator.w3.org/nu/#textarea) and my comments ( [this](https://github.com/onedebos/nyt-clone/pull/6#discussion_r303746226) and [this](https://github.com/onedebos/nyt-clone/pull/6#discussion_r303746886)), this will make the app look even better. 

Good luck with your next project
Keep it up :star2:

Cheers
Bola

2019-07-16 06:39 UTC, bolah2009 commented on styles.css
> +    right: 0;
`SUGGESTION`

Consider adding a bottom border to give the navigation bar a visual separation from the main content of the page:
    `border-bottom: 1px solid <color>;`
Add a z-index to make the navigation bar always atop other elements:
    `z-index: <any integer value>`

#### The app currently looks like this: :point_down: 

![Current App](https://res.cloudinary.com/bolaah/image/upload/v1563258640/github-microverse-project/code-reviews/007.png)

#### Making these changes will make it look like this: :point_down: 

![Prefered Look](https://res.cloudinary.com/bolaah/image/upload/v1563258640/github-microverse-project/code-reviews/006.png)

2019-07-16 06:39 UTC, bolah2009 commented on styles.css
> +    text-decoration: none;
`SUGGESTION`

Consider adding a hover effect like shown below, this makes it look even more like the original app.

![Hover effect](https://res.cloudinary.com/bolaah/image/upload/v1563048062/github-microverse-project/code-reviews/003.gif)

2019-07-16 15:40 UTC, fatymahmed commented on styles.css
> +    text-decoration: none;
Thank you for the suggestions.
we've made the changes.

2019-07-16 15:40 UTC, merged